-- MySQL Script generated by MySQL Workbench
-- Thu Aug  5 17:55:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Linke[DI]n
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Linke[DI]n
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Linke[DI]n` DEFAULT CHARACTER SET utf8 ;
USE `Linke[DI]n` ;

-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Information Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Information Page` (
  `idInformation Page` INT NOT NULL,
  `bio` LONGTEXT NULL,
  `work_experience` MEDIUMTEXT NULL,
  PRIMARY KEY (`idInformation Page`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `profile_picture_dir` TINYTEXT NOT NULL,
  `settings` LONGTEXT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Proffessional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Proffessional` (
  `idProffessional` INT NOT NULL,
  `Information Page_idInformation Page` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idProffessional`),
  INDEX `fk_Proffessional_Information Page1_idx` (`Information Page_idInformation Page` ASC) VISIBLE,
  INDEX `fk_Proffessional_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Proffessional_Information Page1`
    FOREIGN KEY (`Information Page_idInformation Page`)
    REFERENCES `Linke[DI]n`.`Information Page` (`idInformation Page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proffessional_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Linke[DI]n`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Moderator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Moderator` (
  `idModerator` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idModerator`),
  INDEX `fk_Moderator_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Moderator_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Linke[DI]n`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Moderator_moderates_Proffessional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Moderator_moderates_Proffessional` (
  `Moderator_idModerator` INT NOT NULL,
  `Proffessional_idProffessional` INT NOT NULL,
  PRIMARY KEY (`Moderator_idModerator`, `Proffessional_idProffessional`),
  INDEX `fk_Moderator_has_Proffessional_Proffessional1_idx` (`Proffessional_idProffessional` ASC) VISIBLE,
  INDEX `fk_Moderator_has_Proffessional_Moderator_idx` (`Moderator_idModerator` ASC) VISIBLE,
  CONSTRAINT `fk_Moderator_has_Proffessional_Moderator`
    FOREIGN KEY (`Moderator_idModerator`)
    REFERENCES `Linke[DI]n`.`Moderator` (`idModerator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moderator_has_Proffessional_Proffessional1`
    FOREIGN KEY (`Proffessional_idProffessional`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Post` (
  `idPost` INT NOT NULL,
  `Proffessional_idProffessional` INT NOT NULL,
  `title` TINYTEXT NOT NULL,
  `body` LONGTEXT NULL,
  INDEX `fk_Post_Proffessional1_idx` (`Proffessional_idProffessional` ASC) VISIBLE,
  PRIMARY KEY (`idPost`),
  CONSTRAINT `fk_Post_Proffessional1`
    FOREIGN KEY (`Proffessional_idProffessional`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Job_Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Job_Offer` (
  `idJob_Offer` INT NOT NULL,
  `Proffessional_idProffessional` INT NOT NULL,
  `title` TINYTEXT NOT NULL,
  `body` LONGTEXT NULL,
  INDEX `fk_Job Offer_Proffessional1_idx` (`Proffessional_idProffessional` ASC) VISIBLE,
  PRIMARY KEY (`idJob_Offer`),
  CONSTRAINT `fk_Job Offer_Proffessional1`
    FOREIGN KEY (`Proffessional_idProffessional`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Interest_Declaration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Interest_Declaration` (
  `Proffessional_idProffessional` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  INDEX `fk_Interest_Declaration_Proffessional1_idx` (`Proffessional_idProffessional` ASC) VISIBLE,
  PRIMARY KEY (`Proffessional_idProffessional`, `Post_idPost`),
  CONSTRAINT `fk_Interest_Declaration_Proffessional1`
    FOREIGN KEY (`Proffessional_idProffessional`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interest_Declaration_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Linke[DI]n`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Connected`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Connected` (
  `Proffessional_idProffessional1` INT NOT NULL,
  `Proffessional_idProffessional2` INT NOT NULL,
  PRIMARY KEY (`Proffessional_idProffessional1`, `Proffessional_idProffessional2`),
  INDEX `fk_Proffessional_has_Proffessional_Proffessional2_idx` (`Proffessional_idProffessional2` ASC) VISIBLE,
  INDEX `fk_Proffessional_has_Proffessional_Proffessional1_idx` (`Proffessional_idProffessional1` ASC) VISIBLE,
  CONSTRAINT `fk_Proffessional_has_Proffessional_Proffessional1`
    FOREIGN KEY (`Proffessional_idProffessional1`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proffessional_has_Proffessional_Proffessional2`
    FOREIGN KEY (`Proffessional_idProffessional2`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Comment` (
  `Proffessional_idProffessional` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`Proffessional_idProffessional`, `Post_idPost`),
  INDEX `fk_Comment_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Proffessional1`
    FOREIGN KEY (`Proffessional_idProffessional`)
    REFERENCES `Linke[DI]n`.`Proffessional` (`idProffessional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Linke[DI]n`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Picture` (
  `idPictures` INT NOT NULL,
  `picture_dir` TINYTEXT NOT NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`idPictures`),
  INDEX `fk_Picture_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Picture_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Linke[DI]n`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Linke[DI]n`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Linke[DI]n`.`Video` (
  `idVideo` INT NOT NULL,
  `video_dir` TINYTEXT NOT NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`idVideo`),
  INDEX `fk_Video_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Video_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Linke[DI]n`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
